book-category model
literandltx/book-store pull request #7
Opened 2023-09-25 16:55 UTC by literandltx

2023-09-25 17:53 UTC, aaananas requested changes

2023-09-25 17:53 UTC, aaananas commented on src/main/java/com/example/bookstore/service/category/CategoryServiceImpl.java
> +        category.setDescription(request.getDescription());
use mapper

2023-09-26 09:54 UTC, Rommelua commented on src/main/java/com/example/bookstore/service/book/BookServiceImpl.java
> +        Book book = bookMapper.toModel(requestDto);
```suggestion
    public BookDto updateById(Long id, CreateBookRequestDto requestDto) {
        if (!repository.existsById(id)) {
            throw new EntityNotFoundException("Can't found book with id: " + id);
        }
        Book book = bookMapper.toModel(requestDto);
```

2023-09-26 09:54 UTC, Rommelua commented on src/main/java/com/example/bookstore/service/category/CategoryServiceImpl.java
> +        Category category = categoryMapper.toEntity(request);
same

2023-09-26 11:20 UTC, merged